import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ErrorBoundaryWrapper } from "@/components";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <Theme>
          <ErrorBoundaryWrapper>{children}</ErrorBoundaryWrapper>
        </Theme>
      </body>
    </html>
  );
}
