import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import "@/app/globals.css";
import { ErrorBoundaryWrapper } from "@/components";

export const metadata: Metadata = {
  title: "Create Cartify Layout",
  description: "Generated by create Cartify Layout",
};

export default function CartifyLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Theme>
      <ErrorBoundaryWrapper>{children}</ErrorBoundaryWrapper>
    </Theme>
  );
}
